In [14]:
import os
import pandas as pd
import numpy as np

import sys
sys.path.append("..") 

from src import CONST

In [22]:
df = pd.read_feather(os.path.join(CONST.INDIR, "new_merchant_transactions.feather"))[:1000]

/home/sakusaku/anaconda3/envs/elo/lib/python3.6/site-packages/pandas/io/feather_format.py:124: FutureWarning: `nthreads` argument is deprecated, pass `use_threads` instead
  nthreads=int_use_threads)
/home/sakusaku/anaconda3/envs/elo/lib/python3.6/site-packages/pyarrow/pandas_compat.py:751: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels, = index.labels

In [23]:
df.head()

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
0,1,C_ID_415bb3a509,107,0,1,B,307,M_ID_b0c793002c,1,-0.557574,2018-03-11 14:57:36,1.0,9,19
1,1,C_ID_415bb3a509,140,0,1,B,307,M_ID_88920c89e8,1,-0.569580,2018-03-19 18:53:37,1.0,9,19
2,1,C_ID_415bb3a509,330,0,1,B,507,M_ID_ad5237ef6b,2,-0.551037,2018-04-26 14:08:44,1.0,9,14
3,1,C_ID_415bb3a509,-1,1,1,B,661,M_ID_9e84cda3b1,1,-0.671925,2018-03-07 09:43:21,NaN,-1,8
4,1,C_ID_ef55cf8d4b,-1,1,1,B,166,M_ID_3c86fa3831,1,-0.659904,2018-03-22 21:07:53,NaN,-1,29

In [24]:
df[df.card_id == 'C_ID_ef55cf8d4b'].sort_values('purchase_date', ascending=False)[:5]

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
17,1,C_ID_ef55cf8d4b,69,0,1,B,560,M_ID_a1183a4e5e,2,-0.690228,2018-04-22 15:00:27,1.0,9,34
15,1,C_ID_ef55cf8d4b,231,0,1,B,80,M_ID_ad15049b64,2,-0.646245,2018-04-18 12:41:48,1.0,9,37
13,1,C_ID_ef55cf8d4b,69,0,1,B,157,M_ID_28fbc8c74d,2,-0.492058,2018-04-14 09:27:45,1.0,9,29
8,1,C_ID_ef55cf8d4b,69,0,1,B,278,M_ID_d15eae0468,2,-0.596643,2018-04-07 18:37:40,1.0,9,37
22,1,C_ID_ef55cf8d4b,231,0,1,B,360,M_ID_532b2abc39,2,-0.432253,2018-04-06 13:28:22,1.0,9,34

In [47]:
def recent_5_transactions(x):
    x = x.sort_values('purchase_date', ascending=False)[:5]
    return {
        'recent5_authorize_flag-mean': x.authorized_flag.mean(),
        'recent5_city_id-nunique': x.city_id.nunique(),
        'recent5_merchant_category_id-nunique': x.merchant_category_id.nunique(),
        'recent5_purchase_amount-sum': x.purchase_amount.sum(),
        'recent5_purchase_amount-mean': x.purchase_amount.mean(),
        'recent5_installments-sum': x.installments.sum(),
        'recent5_diff_fam-purchase_date-sum': x['diff_fam-purchase_date'].sum(),
        'recent5_diff_fam-purchase_date-min': x['diff_fam-purchase_date'].min(),
        'recent5_diff_fam-purchase_date-max': x['diff_fam-purchase_date'].max(),
        'recent5_diff_fam-purchase_date-mean': x['diff_fam-purchase_date'].mean(),
        'recent5_diff_refdate-purchase_date-sum': x['diff_refdate-purchase_date'].sum(),
        'recent5_diff_refdate-purchase_date-min': x['diff_refdate-purchase_date'].min(),
        'recent5_diff_refdate-purchase_date-max': x['diff_refdate-purchase_date'].max(),
        'recent5_diff_refdate-purchase_date-mean': x['diff_refdate-purchase_date'].mean(),
    }

In [49]:
df = df.sort_values('purchase_date').groupby(['card_id']).tail(5)

In [50]:
df

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id,diff_refdate-purchase_date
721,1,C_ID_3820db9e00,158,0,0,A,614,M_ID_2a12d9a9d6,2,-0.488602,2017-07-03 13:58:44,1.0,15,29,301 days 10:01:16
723,1,C_ID_3820db9e00,158,0,0,A,87,M_ID_52f6d182e2,2,-0.701979,2017-07-03 14:06:20,1.0,15,27,301 days 09:53:40
726,1,C_ID_3820db9e00,158,0,0,A,307,M_ID_f327d5e166,2,-0.701828,2017-07-03 14:41:57,1.0,15,19,301 days 09:18:03
727,1,C_ID_3820db9e00,158,0,0,A,367,M_ID_7cb64bc77b,2,-0.717170,2017-07-03 15:43:00,1.0,15,16,301 days 08:17:00
720,1,C_ID_3820db9e00,158,0,0,A,443,M_ID_1657c15e93,2,-0.562172,2017-07-15 12:33:13,1.0,15,21,289 days 11:26:47
545,1,C_ID_61ad67c5f7,147,0,1,B,705,M_ID_5154015383,2,-0.735938,2017-08-11 15:58:10,3.0,19,33,262 days 08:01:50
624,1,C_ID_a120d34189,143,0,0,A,506,M_ID_a9d91682ad,2,-0.335091,2017-08-12 12:01:54,5.0,5,30,261 days 11:58:06
638,1,C_ID_a120d34189,87,0,0,A,690,M_ID_e266ac2f6e,2,-0.475529,2017-08-12 19:14:50,3.0,11,1,261 days 04:45:10
627,1,C_ID_a120d34189,87,0,0,A,68,M_ID_38d523d3f3,2,-0.583119,2017-08-12 19:37:17,3.0,11,27,261 days 04:22:43
623,1,C_ID_a120d34189,87,0,0,A,278,M_ID_0ec3b78ea3,2,-0.686817,2017-08-12 19:51:17,3.0,11,37,261 days 04:08:43
550,1,C_ID_61ad67c5f7,137,0,1,B,706,M_ID_a9b9f431c7,2,-0.692812,2017-08-19 10:26:30,3.0,19,26,254 days 13:33:30
532,1,C_ID_61ad67c5f7,137,0,1,B,195,M_ID_d475362374,2,-0.650738,2017-08-27 08:35:54,3.0,19,34,246 days 15:24:06
625,1,C_ID_a120d34189,87,0,0,A,605,M_ID_cf33b5cd54,2,-0.145847,2017-08-29 14:34:32,3.0,11,2,244 days 09:25:28
537,1,C_ID_61ad67c5f7,137,0,1,B,307,M_ID_65e406b9d0,2,-0.596643,2017-08-30 18:44:51,3.0,19,19,243 days 05:15:09
524,1,C_ID_61ad67c5f7,137,0,1,B,80,M_ID_f4322bb36d,2,-0.738192,2017-08-30 20:14:25,3.0,19,37,243 days 03:45:35
181,1,C_ID_95bea8a938,19,0,0,A,108,M_ID_1c8cd070e3,2,-0.533396,2017-09-01 11:47:57,1.0,9,34,241 days 12:12:03
180,1,C_ID_95bea8a938,291,0,0,A,511,M_ID_9139332ccc,2,-0.470420,2017-09-05 16:28:06,1.0,9,7,237 days 07:31:54
183,1,C_ID_95bea8a938,19,0,0,A,307,M_ID_b6b55dbeb2,2,-0.686802,2017-09-13 17:01:36,1.0,9,19,229 days 06:58:24
176,1,C_ID_95bea8a938,314,0,0,A,278,M_ID_f4a5c4200a,2,-0.707012,2017-09-14 15:13:08,1.0,9,37,228 days 08:46:52
184,1,C_ID_95bea8a938,199,0,0,A,278,M_ID_87c3f9fccc,2,-0.716103,2017-09-19 16:53:35,4.0,14,37,223 days 07:06:25
324,1,C_ID_c08881d71e,233,0,0,A,307,M_ID_deda8751cf,2,-0.709342,2017-11-14 13:44:11,1.0,9,19,167 days 10:15:49
326,1,C_ID_c08881d71e,233,0,0,A,419,M_ID_58e6eab861,2,-0.731881,2017-11-21 00:00:00,1.0,9,1,161 days 00:00:00
328,1,C_ID_c08881d71e,233,0,0,A,68,M_ID_555f77c85b,2,-0.682294,2017-11-21 00:00:00,1.0,9,27,161 days 00:00:00
321,1,C_ID_c08881d71e,233,0,0,A,690,M_ID_15614da407,2,-0.717005,2017-11-25 14:26:26,1.0,9,1,156 days 09:33:34
331,1,C_ID_c08881d71e,233,0,0,A,518,M_ID_2e3905c2c3,2,-0.710844,2017-11-25 14:45:42,1.0,9,27,156 days 09:14:18
92,1,C_ID_0a6ceeffcc,143,0,0,A,278,M_ID_49d35a5b24,2,-0.713549,2017-12-09 11:37:54,5.0,5,37,142 days 12:22:06
95,1,C_ID_0a6ceeffcc,143,0,0,A,560,M_ID_a581126f45,2,-0.709492,2017-12-09 18:40:38,5.0,5,34,142 days 05:19:22
742,1,C_ID_cb123befc4,69,0,1,B,68,M_ID_3f78680e1c,1,-0.716855,2017-12-13 13:47:52,1.0,9,27,138 days 10:12:08
741,1,C_ID_cb123befc4,69,0,1,B,63,M_ID_8d458948c3,1,-0.719860,2017-12-13 16:12:10,1.0,9,27,138 days 07:47:50
738,1,C_ID_cb123befc4,69,0,1,B,130,M_ID_c355870ab2,1,-0.701828,2017-12-16 13:01:22,1.0,9,41,135 days 10:58:38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,1,C_ID_18c53fe97a,107,0,1,B,278,M_ID_50b2e52eb9,2,-0.656899,2018-04-28 19:14:20,4.0,4,37,2 days 04:45:40
917,1,C_ID_89b91daa95,143,0,1,B,842,M_ID_68c75b8804,2,-0.722039,2018-04-28 19:40:32,5.0,5,37,2 days 04:19:28
284,1,C_ID_086fe1da99,69,0,1,B,437,M_ID_ca4d18b336,2,0.673639,2018-04-28 19:49:40,1.0,9,15,2 days 04:10:20
373,1,C_ID_bb43f4f97a,291,0,0,A,80,M_ID_4cd0ebdcdb,2,-0.730379,2018-04-28 20:27:19,1.0,9,37,2 days 03:32:41
943,1,C_ID_38bd7c7f78,234,0,1,B,278,M_ID_d02228df83,2,-0.602653,2018-04-28 21:53:44,5.0,21,37,2 days 02:06:16
470,1,C_ID_2bba08c2c4,17,0,1,B,278,M_ID_787118d4d4,2,-0.464259,2018-04-28 23:55:05,4.0,22,37,2 days 00:04:55
437,1,C_ID_e6928d4b95,233,0,1,B,842,M_ID_b98db225f5,2,-0.734887,2018-04-29 09:24:53,1.0,9,37,1 days 14:35:07
893,1,C_ID_89b91daa95,143,0,1,B,278,M_ID_889cc3b102,2,-0.616327,2018-04-29 11:04:55,5.0,5,37,1 days 12:55:05
272,1,C_ID_086fe1da99,139,0,1,B,774,M_ID_cbadbaf468,2,-0.625944,2018-04-29 11:35:42,1.0,9,29,1 days 12:24:18
283,1,C_ID_086fe1da99,139,0,1,B,842,M_ID_8dd3f2e24a,2,-0.690709,2018-04-29 11:54:06,1.0,9,37,1 days 12:05:54
696,1,C_ID_da88b91cbc,-1,0,1,B,80,M_ID_540344039a,2,-0.625644,2018-04-29 12:10:18,NaN,-1,37,1 days 11:49:42
578,1,C_ID_83a35c67e9,160,0,0,A,195,M_ID_a6501393ac,2,-0.715277,2018-04-29 13:23:54,5.0,21,34,1 days 10:36:06
793,1,C_ID_b1f2ab5e6b,17,0,1,B,80,M_ID_3f010ea8fd,2,-0.671204,2018-04-29 15:25:09,4.0,22,37,1 days 08:34:51
791,1,C_ID_b1f2ab5e6b,17,0,1,B,834,M_ID_50a3ec0e34,2,-0.611819,2018-04-29 17:28:26,4.0,22,27,1 days 06:31:34
929,1,C_ID_89b91daa95,143,0,1,B,278,M_ID_72609c723e,2,-0.695818,2018-04-29 18:04:02,5.0,5,37,1 days 05:55:58
865,1,C_ID_56fb263b38,252,0,1,B,705,M_ID_dbbc706e8c,2,-0.724368,2018-04-30 08:06:48,1.0,15,33,0 days 15:53:12
945,1,C_ID_38bd7c7f78,223,0,1,B,80,M_ID_08b7a2754c,2,-0.655997,2018-04-30 10:16:27,5.0,21,37,0 days 13:43:33
435,1,C_ID_e6928d4b95,233,0,1,B,528,M_ID_ffefc89829,2,-0.671775,2018-04-30 11:07:22,1.0,9,25,0 days 12:52:38
663,1,C_ID_3ab838c7d8,17,0,0,A,278,M_ID_32191766cf,2,-0.706336,2018-04-30 12:09:43,4.0,22,37,0 days 11:50:17
434,1,C_ID_e6928d4b95,233,0,1,B,703,M_ID_06b2b09e0e,2,-0.716855,2018-04-30 14:21:25,1.0,9,29,0 days 09:38:35
370,1,C_ID_bb43f4f97a,69,0,0,A,14,M_ID_6c3db570df,2,-0.596643,2018-04-30 14:26:57,1.0,9,31,0 days 09:33:03
433,1,C_ID_e6928d4b95,233,0,1,B,536,M_ID_d20a48285d,2,-0.733384,2018-04-30 15:37:19,1.0,9,31,0 days 08:22:41
895,1,C_ID_89b91daa95,143,0,1,B,511,M_ID_3522ca0825,2,-0.721288,2018-04-30 16:15:35,5.0,5,7,0 days 07:44:25
361,1,C_ID_e30251715d,150,0,0,A,411,M_ID_357c160060,2,-0.494763,2018-04-30 16:20:56,5.0,5,21,0 days 07:39:04
343,1,C_ID_18c53fe97a,212,0,1,B,278,M_ID_e7609681b9,2,-0.702730,2018-04-30 16:23:24,4.0,4,37,0 days 07:36:36
342,1,C_ID_18c53fe97a,212,0,1,B,292,M_ID_735cbce64c,2,0.229815,2018-04-30 17:19:39,4.0,4,2,0 days 06:40:21
193,1,C_ID_be71a60d23,143,0,0,A,166,M_ID_12c118b802,2,-0.736389,2018-04-30 17:44:44,5.0,5,29,0 days 06:15:16
336,1,C_ID_18c53fe97a,212,0,1,B,367,M_ID_beeb1815a2,2,-0.694195,2018-04-30 20:12:32,4.0,4,16,0 days 03:47:28
916,1,C_ID_89b91daa95,143,0,1,B,278,M_ID_e43e1173d4,2,-0.504230,2018-04-30 20:21:15,5.0,5,37,0 days 03:38:45
369,1,C_ID_bb43f4f97a,291,0,0,A,705,M_ID_29d04f2408,2,-0.681512,2018-04-30 22:15:09,1.0,9,33,0 days 01:44:51